SFBS_SLOTS ?= 61
ccflags-y += -DSFBS_STIMULUS_SLOTS=$(SFBS_SLOTS)

obj-m += rk3588_sf_bruteforce.o
obj-m += rk3588_sf_sampler.o
obj-m += rk3588_sf_probe.o
obj-m += rk3588_sf_crossprobe.o
obj-m += rk3588_sf_ablation.o
obj-m += rk3588_sf_bitscan.o
