#!/usr/bin/env python3
import argparse
import csv
import statistics
from pathlib import Path

import matplotlib.pyplot as plt


def load_samples(csv_path: Path):
    baseline = []
    candidate = []
    metadata = {}

    with csv_path.open("r", encoding="utf-8") as f:
        rows = []
        for line in f:
            if line.startswith("#"):
                key, _, value = line[1:].strip().partition(",")
                metadata[key] = value
            else:
                rows.append(line)
        reader = csv.reader(rows)
        header = next(reader, None)
        expected = ["type", "index", "avg_ticks"] + [f"pa{i}" for i in range(9)]
        if header != expected:
            raise ValueError(f"Unexpected CSV header: {header}")
        for row in reader:
            kind, _idx, avg, *_addresses = row
            value = float(avg)
            if kind == "baseline":
                baseline.append(value)
            elif kind == "candidate":
                candidate.append(value)

    if not baseline or not candidate:
        raise ValueError("CSV does not contain both baseline and candidate samples")
    return baseline, candidate, metadata


def main():
    parser = argparse.ArgumentParser(description="Plot rk3588_sf_sampler CSV distribution")
    parser.add_argument("csv", type=Path, help="CSV path generated by rk3588_sf_sampler")
    parser.add_argument("--out", type=Path, default=Path("rk3588_sf_sampler_distribution.png"),
                        help="Output PNG path")
    parser.add_argument("--bins", type=int, default=80, help="Histogram bins")
    args = parser.parse_args()
    if args.bins <= 0:
        parser.error("--bins must be positive")

    baseline, candidate, metadata = load_samples(args.csv)
    lower = min(min(baseline), min(candidate))
    upper = max(max(baseline), max(candidate))
    if lower == upper:
        lower -= 0.5
        upper += 0.5
    bin_edges = [
        lower + (upper - lower) * i / args.bins
        for i in range(args.bins + 1)
    ]

    plt.figure(figsize=(11, 6))
    plt.hist(baseline, bins=bin_edges, alpha=0.55, density=True,
             label="baseline (distinct low23)")
    plt.hist(candidate, bins=bin_edges, alpha=0.55, density=True,
             label="candidate (same low23)")

    b_median = statistics.median(baseline)
    c_median = statistics.median(candidate)
    plt.axvline(b_median, linestyle="--", linewidth=1.2,
                label=f"baseline median={b_median:.1f}")
    plt.axvline(c_median, linestyle="--", linewidth=1.2,
                label=f"candidate median={c_median:.1f}")

    plt.title("RK3588 SF Sampler Timing Distribution")
    counter = metadata.get("counter", "counter ticks")
    rounds = metadata.get("access_rounds", "?")
    plt.xlabel(f"Average {counter} per 9-address pass ({rounds} rounds)")
    plt.ylabel("Density")
    plt.legend()
    plt.tight_layout()

    args.out.parent.mkdir(parents=True, exist_ok=True)
    plt.savefig(args.out, dpi=180)
    print(f"Saved plot to: {args.out}")
    print(
        f"baseline: n={len(baseline)}, median={b_median:.2f}, "
        f"mean={statistics.fmean(baseline):.2f}"
    )
    print(
        f"candidate: n={len(candidate)}, median={c_median:.2f}, "
        f"mean={statistics.fmean(candidate):.2f}"
    )


if __name__ == "__main__":
    main()
