#!/usr/bin/env python3
import argparse
import csv
import statistics
from pathlib import Path

import matplotlib.pyplot as plt


def load_samples(csv_path: Path):
    baseline = []
    candidate = []
    metadata = {}

    with csv_path.open("r", encoding="utf-8") as csv_file:
        rows = []
        for line in csv_file:
            if line.startswith("#"):
                key, _, value = line[1:].strip().partition(",")
                metadata[key] = value
            else:
                rows.append(line)

    reader = csv.reader(rows)
    header = next(reader, None)
    expected = (
        ["type", "index", "probe_ticks"]
        + [f"pa{i}" for i in range(8)]
        + ["probe_pa"]
    )
    if header != expected:
        raise ValueError(f"Unexpected CSV header: {header}")

    for row in reader:
        kind, _index, ticks, *_addresses = row
        value = float(ticks)
        if kind == "baseline":
            baseline.append(value)
        elif kind == "candidate":
            candidate.append(value)

    if not baseline or not candidate:
        raise ValueError("CSV must contain baseline and candidate samples")
    return baseline, candidate, metadata


def percentile(values, fraction):
    ordered = sorted(values)
    position = (len(ordered) - 1) * fraction
    lower = int(position)
    upper = min(lower + 1, len(ordered) - 1)
    weight = position - lower
    return ordered[lower] * (1.0 - weight) + ordered[upper] * weight


def describe(name, values):
    print(
        f"{name}: n={len(values)}, mean={statistics.fmean(values):.2f}, "
        f"median={statistics.median(values):.2f}, "
        f"p95={percentile(values, 0.95):.2f}"
    )


def main():
    parser = argparse.ArgumentParser(
        description="Plot rk3588_sf_probe baseline/candidate probe latency"
    )
    parser.add_argument("csv", type=Path, help="CSV generated by rk3588_sf_probe")
    parser.add_argument(
        "--out",
        type=Path,
        default=Path("rk3588_sf_probe_distribution.png"),
        help="Output PNG path",
    )
    parser.add_argument("--bins", type=int, default=80, help="Histogram bins")
    args = parser.parse_args()
    if args.bins <= 0:
        parser.error("--bins must be positive")

    baseline, candidate, metadata = load_samples(args.csv)
    lower = min(min(baseline), min(candidate))
    upper = max(max(baseline), max(candidate))
    if lower == upper:
        lower -= 0.5
        upper += 0.5
    edges = [
        lower + (upper - lower) * index / args.bins
        for index in range(args.bins + 1)
    ]

    baseline_median = statistics.median(baseline)
    candidate_median = statistics.median(candidate)
    counter = metadata.get("counter", "counter_ticks")
    rounds = metadata.get("fill_rounds", "?")

    plt.figure(figsize=(11, 6))
    plt.hist(
        baseline,
        bins=edges,
        alpha=0.55,
        density=True,
        label="baseline: distinct low23",
    )
    plt.hist(
        candidate,
        bins=edges,
        alpha=0.55,
        density=True,
        label="candidate: same low23",
    )
    plt.axvline(
        baseline_median,
        linestyle="--",
        linewidth=1.2,
        label=f"baseline median={baseline_median:.1f}",
    )
    plt.axvline(
        candidate_median,
        linestyle="--",
        linewidth=1.2,
        label=f"candidate median={candidate_median:.1f}",
    )
    plt.title(f"RK3588 line[8] reload latency after 8-line fill × {rounds}")
    plt.xlabel(f"Single probe access latency ({counter})")
    plt.ylabel("Density")
    plt.legend()
    plt.tight_layout()

    args.out.parent.mkdir(parents=True, exist_ok=True)
    plt.savefig(args.out, dpi=180)
    print(f"Saved plot to: {args.out}")
    describe("baseline", baseline)
    describe("candidate", candidate)
    print(
        "median delta "
        f"(candidate - baseline): {candidate_median - baseline_median:.2f}"
    )


if __name__ == "__main__":
    main()
