#!/usr/bin/env python3
import argparse
import csv
import statistics
from pathlib import Path

import matplotlib.pyplot as plt


def load_samples(csv_path: Path):
    samples = {
        "same_first_baseline": [],
        "same_first_candidate": [],
        "cross_first_baseline": [],
        "cross_first_candidate": [],
        "same_prefill_baseline": [],
        "same_prefill_candidate": [],
        "cross_prefill_baseline": [],
        "cross_prefill_candidate": [],
        "same_wait_prefill_baseline": [],
        "same_wait_prefill_candidate": [],
        "cross_wait_prefill_baseline": [],
        "cross_wait_prefill_candidate": [],
        "cross_idle_baseline": [],
        "cross_idle_candidate": [],
        "same_baseline": [],
        "same_candidate": [],
        "cross_baseline": [],
        "cross_candidate": [],
    }
    metadata = {}

    with csv_path.open("r", encoding="utf-8") as csv_file:
        rows = []
        for line in csv_file:
            if line.startswith("#"):
                key, _, value = line[1:].strip().partition(",")
                metadata[key] = value
            else:
                rows.append(line)

    reader = csv.reader(rows)
    header = next(reader, None)
    access_items = int(metadata.get("access_items", len(header or []) - 7))
    if access_items <= 0:
        raise ValueError(f"Invalid access_items: {access_items}")
    expected = (
        [
            "type",
            "index",
            "probe_ticks",
            "l1d_refill",
            "l2d_refill",
            "bus_access",
        ]
        + [f"pa{i}" for i in range(access_items)]
        + ["probe_pa"]
    )
    if header != expected:
        raise ValueError(f"Unexpected CSV header: {header}")

    for row in reader:
        kind, _index, ticks, _l1, _l2, _bus, *_addresses = row
        if kind in samples:
            samples[kind].append(float(ticks))

    wait_names = {
        "same_wait_prefill_baseline",
        "same_wait_prefill_candidate",
        "cross_wait_prefill_baseline",
        "cross_wait_prefill_candidate",
    }
    required_names = (
        samples.keys()
        if "prefill_wait_us" in metadata
        else (name for name in samples if name not in wait_names)
    )
    missing = [name for name in required_names if not samples[name]]
    if missing:
        raise ValueError(f"CSV is missing sample types: {', '.join(missing)}")
    return samples, metadata


def percentile(values, fraction):
    ordered = sorted(values)
    position = (len(ordered) - 1) * fraction
    lower = int(position)
    upper = min(lower + 1, len(ordered) - 1)
    weight = position - lower
    return ordered[lower] * (1.0 - weight) + ordered[upper] * weight


def describe(name, values):
    print(
        f"{name}: n={len(values)}, mean={statistics.fmean(values):.2f}, "
        f"median={statistics.median(values):.2f}, "
        f"p95={percentile(values, 0.95):.2f}"
    )


def main():
    parser = argparse.ArgumentParser(
        description="Plot paired same-CPU and cross-CPU probe distributions"
    )
    parser.add_argument(
        "csv", type=Path, help="CSV generated by rk3588_sf_crossprobe"
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=Path("rk3588_sf_crossprobe_distribution.png"),
        help="Output PNG path",
    )
    parser.add_argument("--bins", type=int, default=80, help="Histogram bins")
    args = parser.parse_args()
    if args.bins <= 0:
        parser.error("--bins must be positive")

    samples, metadata = load_samples(args.csv)
    all_values = [value for values in samples.values() for value in values]
    lower = min(all_values)
    upper = max(all_values)
    if lower == upper:
        lower -= 0.5
        upper += 0.5
    edges = [
        lower + (upper - lower) * index / args.bins
        for index in range(args.bins + 1)
    ]

    counter = metadata.get("counter", "counter_ticks")
    rounds = metadata.get("fill_rounds", "?")
    access_items = metadata.get("access_items", "?")
    match_bits = metadata.get("match_bits", "23")
    probe_cpu = metadata.get("probe_cpu", "?")
    stimulus_cpu = metadata.get(
        "stimulus_cpus", metadata.get("stimulus_cpu", "?")
    )
    prefill_wait_us = metadata.get("prefill_wait_us", "0")

    modes = [
        ("same_first", f"Same CPU{probe_cpu}: first cold access"),
        ("cross_first", f"Cross path CPU{probe_cpu}: first cold access"),
        ("same_prefill", f"Same CPU{probe_cpu}: hot before fill"),
        ("cross_prefill", f"Cross path CPU{probe_cpu}: hot before fill"),
        ("same", f"Same CPU{probe_cpu}: reload after fill"),
        (
            "cross",
            f"Cross reload: CPU{stimulus_cpu} fill, CPU{probe_cpu} probe",
        ),
        ("cross_idle", "Cross idle: CPU handshake, zero item accesses"),
    ]
    if "prefill_wait_us" in metadata:
        modes[4:4] = [
            (
                "same_wait_prefill",
                f"Same CPU{probe_cpu}: hot after {prefill_wait_us} us wait",
            ),
            (
                "cross_wait_prefill",
                f"Cross path CPU{probe_cpu}: hot after {prefill_wait_us} us wait",
            ),
        ]
    plot_rows = 5 if "prefill_wait_us" in metadata else 4
    figure, axes = plt.subplots(
        plot_rows, 2, figsize=(14, 4.5 * plot_rows), sharex=True, sharey=True
    )
    for axis, (mode, title) in zip(axes.flat, modes):
        baseline = samples[f"{mode}_baseline"]
        candidate = samples[f"{mode}_candidate"]
        baseline_median = statistics.median(baseline)
        candidate_median = statistics.median(candidate)
        axis.hist(
            baseline,
            bins=edges,
            alpha=0.55,
            density=True,
            label=f"baseline: nonmatching stimulus low{match_bits}",
        )
        axis.hist(
            candidate,
            bins=edges,
            alpha=0.55,
            density=True,
            label=f"candidate: same low{match_bits}",
        )
        axis.axvline(
            baseline_median,
            linestyle="--",
            linewidth=1.2,
            label=f"baseline median={baseline_median:.1f}",
        )
        axis.axvline(
            candidate_median,
            linestyle="--",
            linewidth=1.2,
            label=f"candidate median={candidate_median:.1f}",
        )
        axis.set_title(title)
        axis.set_xlabel(f"Single probe access latency ({counter})")
        axis.legend()
    axes.flat[-1].axis("off")
    axes[0, 0].set_ylabel("Density")
    axes[1, 0].set_ylabel("Density")
    axes[2, 0].set_ylabel("Density")
    axes[3, 0].set_ylabel("Density")
    if plot_rows > 4:
        axes[4, 0].set_ylabel("Density")
    figure.suptitle(
        f"{access_items}-line fill x {rounds}, prefill wait={prefill_wait_us} us"
    )
    figure.tight_layout()

    args.out.parent.mkdir(parents=True, exist_ok=True)
    figure.savefig(args.out, dpi=180)
    print(f"Saved plot to: {args.out}")
    for name, values in samples.items():
        describe(name, values)
    for mode in (
        "same_first",
        "cross_first",
        "same_prefill",
        "cross_prefill",
        "same",
        "cross",
    ):
        baseline_median = statistics.median(samples[f"{mode}_baseline"])
        candidate_median = statistics.median(samples[f"{mode}_candidate"])
        print(
            f"{mode} median candidate-baseline: "
            f"{candidate_median - baseline_median:.2f}"
        )
    for stage in ("first", "prefill", "reload"):
        for kind in ("baseline", "candidate"):
            suffix = "" if stage == "reload" else f"_{stage}"
            same_name = f"same{suffix}_{kind}"
            cross_name = f"cross{suffix}_{kind}"
            same_median = statistics.median(samples[same_name])
            cross_median = statistics.median(samples[cross_name])
            print(
                f"{stage} {kind} median cross-same: "
                f"{cross_median - same_median:.2f}"
            )


if __name__ == "__main__":
    main()
